routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/privacy', function () {
    return view('privacy');
});

// Auth::routes();

Route::auth();

Route::get('/welcome', 'HomeController@index');

Route::get('/home', 'HomeController@home');

Route::get('tos', function () {
    return view('tos');
});

Route::resource('support', 'SupportController');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('uploads', 'UploadsController');
});

Route::get(
    'downloads/download/{id}',
    [
        'as' => 'downloads.download',
        'uses' => 'DownloadsController@download',
    ]
)->middleware('restricted');

Route::group(['middleware' => ['restricted']], function () {
    Route::resource('downloads', 'DownloadsController');
});

// Route::group(['middleware' => ['trainer']], function () {
//     Route::resource('trainers', 'TrainersController');
// });

//Route::resource('contact', 'ContactController');

Route::get(
    'contact',
    [
    'as' => 'contact.create',
    'uses' => 'ContactController@create',
    ]
);

Route::post(
    'contact',
    [
    'as' => 'contact.store',
    'uses' => 'ContactController@store',
    ]
);

Route::resource('excel', 'ExcelController');

Route::resource('files', 'FilesController');

Route::resource('projectfiles', 'ProjectFilesController');

Route::group(
    [
        'namespace' => 'Admin',
    ],
    function () {
        Route::put(
            'users/{id}/privacy',
            [
            'as' => 'users.privacy',
            'uses' => 'UsersController@updatePrivacy',
            ]
        );
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::resource('snippets', 'SnippetsController');
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'admin',
    ],
    function () {
        Route::resource('privacies', 'PrivaciesController');

        Route::resource('users', 'UsersController');

        Route::resource('clients', 'ClientsController');

        Route::resource('files', 'FilesController');

        Route::resource('projects', 'ProjectsController');

        Route::resource('sites', 'SitesController');

        Route::get('token-settings', 'TokenSettingsController@index')->name('token-settings');

        //get closed
        Route::get('closed-clients', 'ClientsController@closed')->name('closed-clients');
        Route::get('closed-files', 'FilesController@closed')->name('closed-files');
        Route::get('closed-projects', 'ProjectsController@closed')->name('closed-projects');
        Route::get('closed-sites', 'SitesController@closed')->name('closed-sites');
        Route::get('closed-users', 'UsersController@closed')->name('closed-users');

        //put restore - individual

        Route::put(
            'clients/restore/{clientId}',
            [
              'as' => 'clients.restore',
              'uses' => 'ClientsController@restore',
            ]
        );

        Route::put(
            'projects/restore/{projectId}',
            [
              'as' => 'projects.restore',
              'uses' => 'ProjectsController@restore',
            ]
        );

        Route::put(
            'files/restore/{fileId}',
            [
              'as' => 'files.restore',
              'uses' => 'FilesController@restore',
            ]
        );

        Route::put(
            'sites/restore/{siteId}',
            [
              'as' => 'sites.restore',
              'uses' => 'SitesController@restore',
            ]
        );

        Route::put(
            'users/restore/{userId}',
            [
              'as' => 'users.restore',
              'uses' => 'UserController@restore',
            ]
        );

        //delete or restore all files for project
        Route::delete(
            'files/destroy-for-project/{projectId}',
            [
            'as' => 'files.destroy-for-project',
            'uses' => 'FilesController@destroyForProject',
            ]
        );

        Route::put(
            'files/restore-for-project/{projectId}',
            [
            'as' => 'files.restore-for-project',
            'uses' => 'FilesController@restoreForProject',
            ]
        );
    }
);

Route::get('uploader', 'UploadsController@uploader')->name('uploader');
Route::post('uploader-store', 'UploadsController@uploaderStore')->name('uploader-store');

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::post(
            'files/{file}/reviews/parent',
            [
            'as' => 'files.reviews.parent',
            'uses' => 'ReviewsController@parent',
            ]
        );

        Route::resource('files.reviews', 'ReviewsController');
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::get(
            'projects/{id}/getsites',
            [
            'as' => 'users.getsites',
            'uses' => 'ProjectsController@getsites',
            ]
        );
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::post(
            'files/{file}/reviews/namefields',
            [
            'as' => 'files.reviews.namefields',
            'uses' => 'ReviewsController@namefields',
            ]
        );

        Route::resource('files.reviews', 'ReviewsController');
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::resource('files.reviews', 'ReviewsController');
    }
);

app/Http/Controllers/ProjectFilesController.php
<?php

namespace App\Http\Controllers;

use App\File;
use App\Site;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProjectFilesController extends Controller
{
    public function index(Request $request)
    {
        $sites = Site::whereIn('project_id', Auth::user()->projects->pluck('id'))->pluck('id');

        $hasSortBy = $request->has('sort_by');
        $sortBy = $hasSortBy ? $request->get('sort_by') : 'created_at';

        //  Display files with a parent of 0 and a file type of Study

        $query = File::whereIn('site_id', $sites)->where('parent_id', 0)->where('file_type', 'Study');

        if ($hasSortBy) {
            $query->orderBy($sortBy, 'asc');
        } else {
            $query->orderBy('created_at', 'desc');
        }

        if ($request->has('project_id') && $request->get('project_id') != null) {
            $query->where('project_id', $request->get('project_id'));
        }

        $files = $query->get();

        $userProjects = Auth::user()->projects;

        return view('projectfiles.index')->with([
            'files'=> $files,
            'project_id'=> $request->has('project_id') ? $request->get('project_id') : '',
            'userProjects'=>$userProjects,
            'sortBy' => $sortBy,
            ]);
    }

    public function show($id)
    {
        $file = File::findOrFail($id);

        return view('projectfiles.show')->with('file', $file);
    }
}

resources/views/projectfiles/index.blade.php
<!--Project Files Index -->

@extends ('layouts.app')

@section ('content')

    <div class="page-header">
        <div class="container clearfix">
            <h1>Your Project Files</h1>
            {!! link_to_route('excel.index', 
                  'Export to Excel', 
                  ['project_id' => isset($project_id) ? $project_id : ''], 
                  ['class' => 'btn btn-primary pull-right']) 
            !!}
        </div>
        
    </div>

    @if(count($userProjects)>1)
    <div class="container clearfix">
        {!! Form::open(['route' => 'projectfiles.index', 'method' => 'get', 'id' => 'tip-form', 'class' => 'form', 'novalidate' => 'novalidate', 'files' => false]) !!}

    <div class="form-group hidden-print">
        {!!Form::label('project_id','Filter by Project')!!}
         {!! Form::select(
                   'project_id',
                    $userProjects->mapWithKeys(function ($project, $key) { return [$project->id => "(ID: " .$project->id. ") " . $project->name];})->all(),
                    null, 
            ['placeholder' => 'Select Site', 'class' => 'form-control'])!!}
    </div>
    
   
    
    <div class="btn-group float-left">
        {!! Form::submit('Filter', array('class'=>'btn btn-info hidden-print')) !!}
    
        <a href="/admin/files" class="btn btn-success hidden-print">Clear Filter</a>
    </div>

    
    {!! Form::close() !!}
    
    </div>
    @endif

    
        @if ($files->count() > 0)

        <table class="table table-striped table-hover">
            <thead>
              <tr>
                    <th>Key</th>
                    <th>File Type</th>
                    <th>Status</th>

                    <th>
                        <a href="{{Request::fullUrlWithQuery(['sort_by' => 'name'])}}" class="{{ $sortBy == 'name' ? 'text-info' : '' }}">File Name</a>
                    </th>                    
                    
                    <th>Site Name</th>
                    <th>Site ID</th>
                    <th>Subject</th>
                    <th>Visit</th>
                    <th>EEG Date</th>

                    <th>
                        <a href="{{Request::fullUrlWithQuery(['sort_by' => 'created_at'])}}" class="{{ $sortBy == 'created_at' ? 'text-info' : '' }}">Upload Date</a>
                    </th>
                    
                    <th>Rating</th>
                    <th></th>
              </tr>
            </thead>
            
            <tbody>
    
                @foreach ($files as $file)
               
                <tr style="list-style: none;">
                    
                    <td>
                        {!! link_to_route('files.edit', $file->id, [ $file->id ]) !!}
                    </td>
                    
                    <td>
                        @if (! is_null($file->file_type))
                            {{ $file->file_type }}
                        @else
                            &nbsp;
                        @endif
                    </td>
                    
                    <td>
                        @if (! is_null($file->status))
                            {{ $file->status }}
                        @else
                            &nbsp;
                        @endif
                    </td>
                    
                    <td>
                        {{ $file->fileExtensionStrip() }} 
                    </td>

                    <td>
                        {{ $file->site->name }}
                    </td>
                    
                    <td>
                        {{ $file->site->identifier }}
                    </td>
   
                    <td>
                        @if (! is_null($file->subject_id))
                            {{ $file->subject_id }}
                        @else
                            &nbsp;
                        @endif
                    </td>
                    
                    <td>
                        @if (! is_null($file->subject_visit))
                            {{ $file->subject_visit }}
                        @else
                            &nbsp;
                        @endif
                    </td>
 
                    <td>
                        {{ $file->eeg_date }}
                    </td>
                    
                    <td>
                        {{ $file->created_at }}
                    </td>
                    
                    <td>
                        {{ $file->rating }}
                    </td>
                
                    <td>
                        {!! link_to_route('projectfiles.show', "Show", [$file->id],['class' => 'btn btn-secondary btn-sm hidden-print']) !!}
                    </td>

            @endforeach
        </tbody>
      </table> 

    @else
    
        <p>
            No files found!
        </p>
        
    @endif


    
@endsection

resources/views/projectfiles/show.blade.php
<!--Project Files Show-->

@extends ('layouts.app')

@section ('content')

<div class="page-header">
    <div class="container">
        <h1>File Information {{ $file->fileId }}</h1>
    </div>
</div>

<div class="container clearfix mb-4">
    <table class="table">
    
        <!-- File Name Less Extension -->        
        <tr>
            <th>Name:</th>
            <td>{{ $file->fileExtensionStrip() }} </td>
        </tr>
        
         <!-- Site Number -->                   
        <tr>
            <th>Site:</th>
            <td>{{ $file->site->identifier }}</td>
        </tr>
        
        <!-- File Type-->
        <tr>
            <th>Type:</th>
            <td>
                @if (! is_null($file->file_type))
                    {{ $file->file_type }}
                    @else
                        &nbsp;
                @endif
            </td>
        </tr>
        
        <!-- Uploaded By -->  
        <tr>
            <th>Uploaded&nbsp;By:</th>
            <td>{{ $file->user->fullName }} ({{ $file->user->email }})</td>
        </tr>
        
        <!-- File Internal Record Number -->    
        <tr>
            <th>Internal&nbsp;Id:</th>
            <td>{{ $file->id }}</td>
        </tr>   

        <tr>
            <th>Quality&nbsp;Rating:</th>
            <td>
                @if (! is_null($file->rating))
                    {{ $file->rating }}
                    @else
                        &nbsp;
                @endif
            </td>        
        </tr>

        <!-- Reviwer Comments -->
        <tr>
            <th>Reviewer&nbsp;Feedback:</th>
            <td>
                @if (! is_null($file->reviewer_notes))
                    {{ $file->reviewer_notes }}
                    @else
                        &nbsp;
                @endif
            </td>        
        </tr>
 
         <!-- Quality Category -->
        <tr>
            <th>Quality&nbsp;Category:</th>
            <td>
                @if (! is_null($file->qualityCategory))
                    {{ $file->qualityCategory }}
                    @else
                        &nbsp;
                @endif
            </td>        
        </tr>
        
         <!-- Status -->
        <tr>
            <th>Internal&nbsp;Status:</th>
            <td>
                @if (! is_null($file->status))
                    {{ $file->status }}
                    @else
                        &nbsp;
                @endif
            </td>        
        </tr>
        
         <!-- Comments -->
        <tr>
            <th>Internal&nbsp;Comment:</th>
            <td>
                @if (! is_null($file->comment))
                    {{ $file->comment }}
                    @else
                        &nbsp;
                @endif
            </td>        
        </tr>    
        


    </table>
    {!! link_to_route('projectfiles.index', "Project Files Home", null, ['class' => 'btn btn-primary float-right'] ) !!}
</div>


@endsection