routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/privacy', function () {
    return view('privacy');
});

// Auth::routes();

Route::auth();

Route::get('/welcome', 'HomeController@index');

Route::get('/home', 'HomeController@home');

Route::get('tos', function () {
    return view('tos');
});

Route::resource('support', 'SupportController');

Route::group(['middleware' => ['auth']], function () {
    Route::resource('uploads', 'UploadsController');
});

Route::get(
    'downloads/download/{id}',
    [
        'as' => 'downloads.download',
        'uses' => 'DownloadsController@download',
    ]
)->middleware('restricted');

Route::group(['middleware' => ['restricted']], function () {
    Route::resource('downloads', 'DownloadsController');
});

// Route::group(['middleware' => ['trainer']], function () {
//     Route::resource('trainers', 'TrainersController');
// });

//Route::resource('contact', 'ContactController');

Route::get(
    'contact',
    [
    'as' => 'contact.create',
    'uses' => 'ContactController@create',
    ]
);

Route::post(
    'contact',
    [
    'as' => 'contact.store',
    'uses' => 'ContactController@store',
    ]
);

Route::resource('excel', 'ExcelController');

Route::resource('files', 'FilesController');

Route::resource('projectfiles', 'ProjectFilesController');

Route::group(
    [
        'namespace' => 'Admin',
    ],
    function () {
        Route::put(
            'users/{id}/privacy',
            [
            'as' => 'users.privacy',
            'uses' => 'UsersController@updatePrivacy',
            ]
        );
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::resource('snippets', 'SnippetsController');
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'admin',
    ],
    function () {
        Route::resource('privacies', 'PrivaciesController');

        Route::resource('users', 'UsersController');

        Route::resource('clients', 'ClientsController');

        Route::resource('files', 'FilesController');

        Route::resource('projects', 'ProjectsController');

        Route::resource('sites', 'SitesController');

        Route::get('token-settings', 'TokenSettingsController@index')->name('token-settings');

        //get closed
        Route::get('closed-clients', 'ClientsController@closed')->name('closed-clients');
        Route::get('closed-files', 'FilesController@closed')->name('closed-files');
        Route::get('closed-projects', 'ProjectsController@closed')->name('closed-projects');
        Route::get('closed-sites', 'SitesController@closed')->name('closed-sites');
        Route::get('closed-users', 'UsersController@closed')->name('closed-users');

        //put restore - individual

        Route::put(
            'clients/restore/{clientId}',
            [
              'as' => 'clients.restore',
              'uses' => 'ClientsController@restore',
            ]
        );

        Route::put(
            'projects/restore/{projectId}',
            [
              'as' => 'projects.restore',
              'uses' => 'ProjectsController@restore',
            ]
        );

        Route::put(
            'files/restore/{fileId}',
            [
              'as' => 'files.restore',
              'uses' => 'FilesController@restore',
            ]
        );

        Route::put(
            'sites/restore/{siteId}',
            [
              'as' => 'sites.restore',
              'uses' => 'SitesController@restore',
            ]
        );

        Route::put(
            'users/restore/{userId}',
            [
              'as' => 'users.restore',
              'uses' => 'UserController@restore',
            ]
        );

        //delete or restore all files for project
        Route::delete(
            'files/destroy-for-project/{projectId}',
            [
            'as' => 'files.destroy-for-project',
            'uses' => 'FilesController@destroyForProject',
            ]
        );

        Route::put(
            'files/restore-for-project/{projectId}',
            [
            'as' => 'files.restore-for-project',
            'uses' => 'FilesController@restoreForProject',
            ]
        );
    }
);

Route::get('uploader', 'UploadsController@uploader')->name('uploader');
Route::post('uploader-store', 'UploadsController@uploaderStore')->name('uploader-store');

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::post(
            'files/{file}/reviews/parent',
            [
            'as' => 'files.reviews.parent',
            'uses' => 'ReviewsController@parent',
            ]
        );

        Route::resource('files.reviews', 'ReviewsController');
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::get(
            'projects/{id}/getsites',
            [
            'as' => 'users.getsites',
            'uses' => 'ProjectsController@getsites',
            ]
        );
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::post(
            'files/{file}/reviews/namefields',
            [
            'as' => 'files.reviews.namefields',
            'uses' => 'ReviewsController@namefields',
            ]
        );

        Route::resource('files.reviews', 'ReviewsController');
    }
);

Route::group(
    [
        'prefix' => 'admin',
        'namespace' => 'Admin',
        'middleware' => 'adminexpertsystem',
    ],
    function () {
        Route::resource('files.reviews', 'ReviewsController');
    }
);

app/File.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class File extends Model
{
    use SoftDeletes;

    protected $fillable = [

    ];

    // Relationships

    public function site()
    {
        return $this->belongsTo(\App\Site::class)->withTrashed();
    }

    public function user()
    {
        return $this->belongsTo(\App\User::class)->withTrashed();
    }

    public function project()
    {
        return $this->belongsTo(\App\Project::class)->withTrashed();
    }

    public function snippets()
    {
        return $this->belongsToMany(\App\Snippet::class)->withTimestamps();
    }

    // Scopes

    public function scopeByProject($query, $projectID)
    {
        return $query->where('project_id', $projectID);
    }

    public function scopeParentIsZero($query)
    {
        return $query->where('parent_id', 0);
    }

    public function scopeNoRating($query)
    {
        return $query->where('rating', 0);
    }

    // Scopes

    /**
     * Utility to get the file name with out the extension.
     *
     * @returns a {@code String} containing just the filename
     */
    public function fileExtensionStrip()
    {
        return preg_replace('/.[^.]*$/', '', $this->name);
    }
}

app/Http/Controllers/Admin/FilesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\File;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;

class FilesController extends Controller
{
    //Index Display
    public function index(Request $request)
    {
        $hasSortBy = $request->has('sort_by');
        $sortBy = $hasSortBy ? $request->get('sort_by') : 'name';
        $hasShowDeleted = $request->has('show_deleted') && $request->get('show_deleted') != null;

        $query = File::orderBy($sortBy, $sortBy == 'created_at' ? 'desc' : 'asc')
            ->orderBy('created_at', 'desc');

        if ($request->has('project_id') && $request->get('project_id') != null) {
            $query->where('project_id', $request->get('project_id'));
        }

        if ($request->has('site_id') && $request->get('site_id') != null) {
            $query->where('site_id', $request->get('site_id'));
        }

        if ($request->has('file_type') && $request->get('file_type') != null) {
            $query->where('file_type', $request->get('file_type'));
        }

        //if show deleted is checked
        if ($hasShowDeleted) {
            $query->withTrashed();
        }

        $files = $query->get();

        return view('admin.files.index')->with([
            'files' => $files,
            'sortBy' => $sortBy,
            'hasShowDeleted' => $hasShowDeleted,
        ]);
    }

    //Create and Store
    public function create()
    {
        return view('admin.files.create');
    }

    public function store(Request $request)
    {
        $file = new File();

        $file->name = $request->get('name');
        $file->site_id = $request->get('site_id');

        $file->save();

        return Redirect::route('files.index')->with('message', 'File saved!');
    }

    //Show
    public function show($id)
    {
        $file = File::withTrashed()->findOrFail($id);

        return view('admin.files.show')->with('file', $file);
    }

    //Edit
    public function edit($id)
    {
        $file = File::findOrFail($id);

        return view('admin.files.edit')->with('file', $file);
    }

    //Update
    public function update(Request $request, $id)
    {
        $file = File::findOrFail($id);

        if ($request->has('site_id') && $request->get('site_id') != null) {
            $file->site_id = $request->get('site_id');
        }

        if ($request->has('name') && $request->get('name') != null && $request->get('name') != $file->name) {
            $oldFileName = $file->name;
            $newFileName = $request->get('name');
            $file->name = $newFileName;

            $doesFileExist = Storage::disk('s3')->exists('storage/files/'.$oldFileName);
            if ($doesFileExist) {
                Storage::move('storage/files/'.$oldFileName, 'storage/files/'.$newFileName);
            }
        }

        $file->save();

        return Redirect::route('files.edit', [$file->id])->with('message', 'Your File has been updated!');
    }

    public function destroyForProject($projectId)
    {
        /*
         * TODO:
         * Comment out line 137
         **/
        File::where('project_id', $projectId)->delete();

        /*
         * TODO:
         * Add an int column to the files table with the key "deleted_reason"
         * Uncomment lines 144-146
         */
        // $timestamp = Carbon\Carbon::now()->toDateTimeString();
        // $data = ['deleted_at' => $timestamp, 'deleted_reason' => 500];
        // File::where('id', $id)->update($data);

        return back()->with('message', 'Files Deleted!');
    }

    //Restore For Project - all files
    public function restoreForProject($projectId)
    {

        /*
         * TODO: Comment out line 161
         */
        File::where('project_id', $projectId)->onlyTrashed()->restore();

        /*
         * TODO Uncomment Lines 168
         */
        // File::where('project_id', $projectId)->where('deleted_reason', 500)->onlyTrashed()->restore();

        return back()->with('message', 'Files Restored!');
    }

    //Restore - this is not possible if we are actually deleting them
    // public function restore($fileId)
    // {
    //     Project::withTrashed()->find($fileId)->restore();
    //     return back()->with('message', 'File Restored!');
    // }

    //Delete
    public function destroy($id)
    {
        $file = File::findOrFail($id);

        // Storage::delete('storage/files/' . $file->name);  Use soft deletes instead.

        $file->delete();

        return Redirect::route('files.index')->with('message', 'File deleted!');
    }
}

app/Http/Controllers/FilesController.php
<?php

namespace App\Http\Controllers;

use App\File;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class FilesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

         // for a Sort to order by Create Date
        $hasSortBy = $request->has('sort_by') && $request->get('sort_by') != null;
        $hasSiteId = $request->has('site_id') && $request->get('site_id') != null;
        $hasFileType = $request->has('file_type') && $request->get('file_type') != null;
        $hasParentId = $request->has('parent') && is_numeric($request->get('parent'));
        $hasClear = $request->has('clear') && $request->get('clear') != null;

        $sortBy = $hasSortBy ? $request->get('sort_by') : 'name';

        $userSites = Auth::user()->sites;

        $hasSortBy = $request->has('sort_by');
        $sortBy = $hasSortBy ? $request->get('sort_by') : 'created_at';

        $query = File::whereIn('site_id', $userSites->pluck('id'))
            ->orderBy($sortBy, 'desc')
            ->orderBy('name', 'asc');

        if ($hasSiteId) {
            $query->where('site_id', $request->get('site_id'));
        }

        if ($hasFileType) {
            $query->where('file_type', $request->get('file_type'));
        }

        if ($hasParentId) {
            $query->where('parent_id', $request->get('parent'));
        }

        // Set a defuault Query
        $shouldDefault = ! $hasSiteId && ! $hasClear && ! $hasFileType && ! $hasParentId;
        if ($shouldDefault) {
            $query->where('file_type', 'study');
            $query->where('parent_id', 0);
            $hasParentId = true;
        }

        $files = $query->paginate(5000);

        return view('files.index')
            ->with([
                'files' => $files,
                'userSites' => $userSites,
                'hasParentId' => $hasParentId,
                'sortBy' => $sortBy,
            ]);
    }
}

resources/views/admin/files/_delete_confirm.blade.php
<!-- Files - Delete_Confirm Modal Partial -->

<div class="modal fade" id="deleteConfirm" tabindex="-1" role="dialog" aria-labelledby="deleteConfirmLabel"> <!-- id tells Bootstrap which modal to open -->
  
  <div class="modal-dialog" role="document">
    
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="deleteConfirmTitle">Delete File</h4>
      </div>
      
      <div class="modal-body">
        <p>Please confirm you would like to delete this File Record?</p> 
      </div>
      

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      
        {!! Form::open([
            'route' => ['files.destroy', $file->id],
            'class' => 'form', 
            'method' => 'delete',
            'id' => 'tip-form',
            'novalidate' => 'novalidate'
            ]
        ) !!}
         
        <button type="submit" class="btn btn-danger" id="deleteConfirmButton">Delete</button>
         
        {!! Form::close() !!}  
      </div>
    </div>
  </div>
</div>
      

resources/views/admin/files/_file_form.blade.php
<!--File Partial-->

<fieldset>
    
    <div class="form-group">
        {!!Form::label('site_id','Site Id')!!}
        {!! Form::select('site_id', App\Site::orderBy('identifier', 'asc')->pluck('identifier', 'id'),null, ['placeholder' => 'Select Site', 'class' => 'form-control'])!!}
    </div>
    
</fieldset>
<br clear="all" />

resources/views/admin/files/_rename_form.blade.php
<!--File Rename Partial-->

    @php
         $fileName = $file->name;
    @endphp

    <div class="form-group">
        {!!Form::label('name','File Name')!!}
        {!!Form::text('name',$fileName, ['id' =>'name','class' =>'form-control','placeholder' =>'Enter File Name']) !!}
    </div>
    
<br clear="all" />

resources/views/admin/files/_restore_confirm.blade.php
<!-- Files - Restore_Confirm Modal Partial -->

<div class="modal fade" id="restoreConfirm" tabindex="-1" role="dialog" aria-labelledby="restoreConfirmLabel"> <!-- id tells Bootstrap which modal to open -->
  
  <div class="modal-dialog" role="document">
    
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="restoreConfirmTitle">Restore File</h4>
      </div>
      
      <div class="modal-body">
        <p>Please confirm you would like to restore this File.</p> 
      </div>
      

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      
        {!! Form::open([
            'route' => ['projects.restore', $project->id],
            'class' => 'form', 
            'method' => 'put',
            'id' => 'tip-form',
            'novalidate' => 'novalidate'
            ]
        ) !!}
         
         <button type="submit" class="btn btn-danger" id="restoreConfirmButton">Restore</button>
         
        {!! Form::close() !!}  
      </div>
    </div>
  </div>
</div>
      

resources/views/admin/files/create.blade.php
<!--Create A File Record-->


@extends ('layouts.app')

@section ('content')

<div class="page-header">
      <h1>File Upload</h1>
</div>
    
    <div class="container clearfix">
      <div class="row">   

      <div class="col-md-6">
        
        {!! Form::open(['route' => 'files.store', 'id' => 'tip-form', 'class' => 'form', 'novalidate' => 'novalidate', 'files' => false]) !!}
    
        @include('admin.files._file_form')
        
        <div class="form-group">
      	    {!! Form::label('document-1', 'Upload File') !!}
      	    {!! Form::file('document-1', null, ['class'=>'form-control btn btn-lg btn-primary']) !!}
      	</div>
    
        {!! Form::submit('Upload', array('class'=>'btn btn-primary btn-lg hidden-print')) !!}
          
        {!! Form::close() !!}
    
    
            {!! link_to_route('files.index', "Files Home", null, ['class' => 'btn btn-default btn-first btn-lg hidden-print'] ) !!}
    
    
    
      </div>
    </div>
</div>
  
@endsection

resources/views/admin/files/edit.blade.php
<!--Files - Edit-->

@extends ('layouts.app')

@section ('content')

 <div class="page-header">
    <div class="container">
   <h1>Edit {{ $file->name }} (ID:{{ $file->id }}) </h1>
    </div>
</div>

<div class="container clearfix border-bottom pb-4 mb-6"> 
  <div class="row">  
  
      {!! Form::model($file, [
          'route' => ['files.update',$file->id],
          'method' => 'put',
          'id' => 'tip-form', 
          'class' => 'form', 
          'novalidate' => 'novalidate']
      ) !!}

        <div class="col-md-12">
      
          <fieldset >
             @include('admin.files._rename_form')
          </fieldset> 
          


      
          <fieldset >
                @include('admin.files._file_form')
          </fieldset> 
      
        </div>

      <div class="btn-group float-right">
              {!! link_to_route('files.index', "Files Home", null, ['class' => 'btn btn-default btn-first'] ) !!}
                  
              {!! Form::submit('Update File', array('class'=>'btn btn-primary')) !!}  
          
        </div>
    
      
      {!! Form::close() !!}
  
    
  </div>
</div>
@endsection

resources/views/admin/files/index.blade.php
<!--Files Index -->

@extends ('layouts.app')

@section ('content')


    <div class="page-header">
        <div class="container">
            <h1>Files</h1>

        </div>
    </div>
    
    <div class="container clearfix">
        {!! Form::open(['route' => 'files.index', 'method' => 'get', 'id' => 'tip-form', 'class' => 'form', 'novalidate' => 'novalidate', 'files' => false]) !!}

    <div class="form-group hidden-print">
        {!!Form::label('project_id','Filter by Project')!!}
        {!! Form::select('project_id', App\Project::select('id', DB::raw('CONCAT("(ID: ", identifier, ") ", name) AS name'))->pluck('name', 'id'),
        null, 
        ['placeholder' => 'Select Project', 'class' => 'form-control'])!!}
    </div>

    <div class="form-group hidden-print">
        {!!Form::label('site_id','Filter by Site')!!}
        {!! Form::select('site_id', App\Site::select('id', DB::raw('CONCAT("(ID: ", identifier, ") ", name) AS name'))->pluck('name', 'id'),
        null, 
        ['placeholder' => 'Select Site', 'class' => 'form-control'])!!}
    </div>
    
        <div class="form-group hidden-print">
        {!! Form::label('file_type','File Type') !!}
        
        {!! Form::select('file_type',
            [
                'Study' => 'Study',
                'Practice'   => 'Practice',
                'Training'   => 'Training',
                'Courtesy'   => 'Courtesy',
                'Other'      => 'Other'
            ],
            null,
            [
                'id'    => 'file_type',
                'class' =>'form-control',
                'placeholder' => 'Select File Type'
            ]
            
            )!!}
    </div>
    
    <!-- Show Deleted -->
    <div class="form-group hidden-print">
        {!!Form::label('show_deleted','Show Deleted')!!}
        {!!Form::checkbox('show_deleted', 1,  $hasShowDeleted) !!}
    </div>
    
    

    <div class="btn-group float-left">
        {!! Form::submit('Filter', array('class'=>'btn btn-info hidden-print')) !!}
    
        <a href="/admin/files" class="btn btn-success hidden-print">Clear Filter</a>
    </div>
    <a href="{{ route('uploads.create') }}" class="btn btn-primary float-right hidden-print">Upload File</a>

    
    
    {!! Form::close() !!}
    </div>
    
    
    
    @if ($files->count() > 0)
    
        <table class="table table-striped table-hover">
            <thead>
              <tr>
                    <th>Key</th>
                    <th>
                        <a href="{{Request::fullUrlWithQuery(['sort_by' => 'name'])}}" class="{{ $sortBy == 'name' ? 'text-info' : '' }}">File Name</a>
                    </th>
                    <th>File Type</th>
                    <th>
                        <a href="{{Request::fullUrlWithQuery(['sort_by' => 'site_id'])}}" class="{{ $sortBy == 'site_id' ? 'text-info' : '' }}">Site Identifier</a>
                    </th>
                    <th>Site</th>
                    <th>Rating</th>
                    <th>Uploaded By (User)</th>
                    <th>
                        <a href="{{Request::fullUrlWithQuery(['sort_by' => 'created_at'])}}" class="{{ $sortBy == 'created_at' ? 'text-info' : '' }}">Uploaded On</a>
                    </th>
                    <th></th>
              </tr>
            </thead>
            
            <tbody>
    
                @foreach ($files as $file)
               
                <tr style="list-style: none; {{$file->trashed() ? "background-color:#ffe0b2 !important;":''}}" class="{{$file->trashed() ? "bg-warning" : ""}}">
                    
                    <td>{!! link_to_route('files.edit', $file->id, [ $file->id ]) !!}</td>
                    
                    <td>
                        {{ $file->name}}
                    </td>
                    
                    <td>
                        @if (! is_null($file->file_type))
                            {{ $file->file_type }}
                        @else
                             &nbsp;
                        @endif
                    </td>
                    
                    <td>
                        {{ $file->site->identifier }}
                    </td>
                    
                    <td>
                        {{ $file->site->name }}
                    </td>
                    
                    <td>
                        {{ $file->rating }}
                    </td>
                    
                    <td>
                        @if (! is_null($file->user))
                        {{ $file->user->fullName}} ({{ $file->user->email }})
                        @else
                        &nbsp;
                        @endif
                    </td>
                    
                    <td>
                        {{ date("m/d/y", strtotime($file->created_at)) }}
                    </td>

                    <td>
                        <div class="btn-group">
                        {!! link_to_route('files.edit', "Edit", [$file->id], ['class' => 'btn btn-primary btn-sm hidden-print ']) !!}
                    
                        {!! link_to_route('files.show', "Show", [$file->id],['class' => 'btn btn-secondary btn-sm hidden-print ']) !!}
                    
                        {!! link_to_route('files.reviews.edit', "Review", [$file->id, $file->id],['class' => 'btn btn-success btn-sm hidden-print ']) !!}
                        </div>
                    </td>
                    
            @endforeach

        </tbody>
      </table> 


    @else
    
        <p>
            No files found!
        </p>
        
    @endif
    
    <!--{!! link_to_route('uploads.create', "Upload File", null, ['class' => 'hidden-print btn btn-default btn-first'] ) !!}-->
    
@endsection

resources/views/admin/files/show.blade.php
<!--Files Show-->

@extends ('layouts.app')

@section ('content')

<div class="page-header">
    <div class="container">
        <h1>File {{ $file->fileId }}</h1>

    </div>
</div>

<div class="container clearfix mb-4">
    
<table class="table table-striped">
        <thead>
            <tr>
                <th>Description</th>
                <th>Value</th>
            </tr>
        </thead>
        
        <tbody>
            <tr>
                <td>Name</td>
                <td>{{ $file->name }}</td>
            </tr>
            
            <tr>
                <td>Id</td>
                <td>{{ $file->id }}</td>
            </tr>
            
            <tr>
                <td>Site</td>
                <td>{{ $file->site->name }}</td>
            </tr>
    
            <tr>
                <td> Created On</td>
                <td>{{ date("m/d/y", strtotime($file->created_at)) }}</td>
            </tr>
            
            <tr>
                <td>Updated On</td>
                <td>
                    @if (! is_null($file->updated_at))
                        {{ date("m/d/y", strtotime($file->updated_at)) }}
                    @else
                        &nbsp;
                    @endif
                </td>
            </tr>
                
            <tr>
                <td> Deleted On</td>
                <td>
                    @if (! is_null($file->deleted_at))
                        {{ date("m/d/y", strtotime($file->deleted_at)) }}
                    @else
                         &nbsp;
                    @endif
                </td>
            </tr>
            
            <tr>
                <td>Deleted Reason</td>
                <td>{{ $file->deleted_reason }}</td>
            </tr>
    </tbody>
</table>
<br/>

    <div class="btn-group float-right">
        
        {!! link_to_route('files.index', "Files Home", null, ['class' => 'btn btn-default'] ) !!}
    
        {!! link_to_route('files.edit', "Edit File", [$file->id], ['class' => 'btn btn-primary']) !!}
    
         @if (is_null($file->deleted_at))
            <button type='button' data-toggle="modal" data-target="#deleteConfirm" class='btn btn-danger'><i class='glyphicon glyphicon-trash'></i> Delete</button>
        @endif
    </div>
    
</div>

@include('admin.files._delete_confirm')
    
@endsection